export const apiUrl = 'http://192.168.1.19:4000';

export const urls = {
    signup: `${apiUrl}/api/users/`,
    signin: `${apiUrl}/api/users/auth`,
    user: `${apiUrl}/api/users/user`,
    newsupplier: `${apiUrl}/api/suppliers/new`,
    getsuppliers: `${apiUrl}/api/suppliers/get`,
    updatesupplierstatus: `${apiUrl}/api/suppliers/status`,
    updatesupplier: `${apiUrl}/api/suppliers/update`,
    newproducttype: `${apiUrl}/api/producttypes/new`,
    getproducttypes: `${apiUrl}/api/producttypes/get`,
    updateproducttypestatus: `${apiUrl}/api/producttypes/status`,
    updateproducttype: `${apiUrl}/api/producttypes/update`,
    newitem: `${apiUrl}/api/items/new`,
    getitems: `${apiUrl}/api/items/get`,
    getexclude: `${apiUrl}/api/items/exclude`,
    updateitem: `${apiUrl}/api/items/update`,
    disableitem: `${apiUrl}/api/items/status/disable`,
    enableitem: `${apiUrl}/api/items/status/enable`,
    getbatches: `${apiUrl}/api/batches/get`,
    newbatch: `${apiUrl}/api/batches/new`,
    getbatch: `${apiUrl}/api/batches/batch`,
    updatebatch: `${apiUrl}/api/batches/update`,
    batchdata: `${apiUrl}/api/batches/batch-data`,
    newbarcode: `${apiUrl}/api/barcodes/new`,
    neworder: `${apiUrl}/api/orders/new`,
    solditemstoday: `${apiUrl}/api/solditems/today`,
    dateofsolditems: `${apiUrl}/api/solditems/date`,
    newexpense: `${apiUrl}/api/expenses/new`,
    getexpensestoday: `${apiUrl}/api/expenses/today`,
    updateexpense: `${apiUrl}/api/expenses/update`,
    deleteexpense: `${apiUrl}/api/expenses/delete`,
    dateofexpenses: `${apiUrl}/api/expenses/date`,
    dateofreport: `${apiUrl}/api/reports/date`,
    monthlyreport: `${apiUrl}/api/reports/monthly`,
    yearlyreport: `${apiUrl}/api/reports/yearly`,
    printpdf: `${apiUrl}/api/reports/print`,
};
